### ISSUE TITLE
Ügyek menüpontból új vita létrehozása kiborítja

### ISSUE THREAD

**Issue by mendly2** [mkkp/e-demokracia#19]
![kép](https://github.com/mkkp/e-demokracia/assets/147447201/7de17af5-9d6c-4709-94fe-236e0f9bf4c8)

létrehoztam egy "vitát" az "Politikust küldjünk az EP-be vagy szakértőt?" ügy alá.
A fenti képernyőre dobott (itt javasolnám, hogy egyből a vitába dojon, ha cisnálok egyet.

Majd az ügy / viták alatt a saját létrehozott új vitámhoz sem engedett hozzászólni, sem semelyik másikhoz.
![kép](https://github.com/mkkp/e-demokracia/assets/147447201/6df72aad-e6b8-490e-9a2b-f10c78fdcffd)

Hiába klikkelem a viták elemeit, csak kijelöli a szöveget, de nem dob tovább arra a részre, hogy hozzászólhassak.

Kilépés és újrabelogolás után nem jelenik meg a vita amit létrehoztam a "vitáim" alatt (ez lehet hogy nem is volt szándék, de azthiszem ha létrehozok egy vitát annak itt érdemes lenne egyből listázódnia)

![kép](https://github.com/mkkp/e-demokracia/assets/147447201/b1c9a45e-930d-4928-bee9-9ab1f6bba2f1)

és továbbra sem enged beljebb a vitába.

**Comment by robertcsakany** [comment]
A #22 ticket ezt az issue-t okafogyottá teszi
