### ISSUE TITLE
Értékelő szavazás 123-123

### ISSUE THREAD

**Issue by mendly2** [mkkp/e-demokracia#20]
Értékelő szavazás indításánál nem kérdez hogyan szeretnék bármit is értékelni. [1-10? 1-100? amúgy az sem világo amíg el nem indítod, hogy ez egy számokkal fog működni, nem pedig egy "szöveges" értékelésről van szó]

Az 123-123 értékeket eleve beállította a szavazáshoz, mint a screenshoton:

![ertekeloszavazas3](https://github.com/mkkp/e-demokracia/assets/147447201/9c549cbf-459d-4a3f-92eb-41e475a60c57)

Nem tudom amúgy hogy érti a 123-123 minimum maximumot, 122-vel is tudtam szavazni. 100000000000000000-val nem.

![ertekeloszavazas1](https://github.com/mkkp/e-demokracia/assets/147447201/46e0c148-28ba-44ba-9375-cd27408108fb)

![ertekeloszavazas2](https://github.com/mkkp/e-demokracia/assets/147447201/4b9f7ca0-ce6f-426e-90d0-e30567cec94f)

**Comment by robertcsakany** [comment]
Az egy ikon. Az ikont le kell cserelni. A #23 ticket oldja meg a validálás kérdését.
